# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kc < Formula
  desc "Two-panel Kubernetes TUI built entirely with AI"
  homepage "https://github.com/sttts/kc"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/kc/releases/download/v0.5.3/kc_0.5.3_darwin_amd64.tar.gz"
      sha256 "7cf864e3af5335bf66ad6abe98d08cf110b0153e76bbf20fa7e7cf9b263107a8"

      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/kc/releases/download/v0.5.3/kc_0.5.3_darwin_arm64.tar.gz"
      sha256 "d7559674e675e3eb08130d3293eb2b22a0dbdfee7c6a976ca84e8131f435ec4d"

      def install
        bin.install "kc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/kc/releases/download/v0.5.3/kc_0.5.3_linux_amd64.tar.gz"
      sha256 "1c4d35e370dbcd15199a756edbc35ffa24e22ec1b0c34f5b76e56e66f7d59974"
      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/kc/releases/download/v0.5.3/kc_0.5.3_linux_arm64.tar.gz"
      sha256 "1289fe29c1c4b26bc6b043bb7ce36d0f49aaf8be98f60a3b2251927c5e8d20e5"
      def install
        bin.install "kc"
      end
    end
  end

  test do
    system "#{bin}/kc", "--version"
  end
end
