# This file was generated by GoReleaser. DO NOT EDIT.
cask "kc" do
  name "kc"
  desc "Two-panel Kubernetes TUI built entirely with AI"
  homepage "https://github.com/sttts/kc"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kc"

  on_macos do
    on_intel do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
      sha256 "74a5989b2ac931dcb12e066974bb6b4e81164b07bdc399f71e8251e9d1320ad0"
    end
    on_arm do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
      sha256 "d2e74b2c14a1f907f93c776a7b5260186bc84d427d27d4adeb68e03c38772d59"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
      sha256 "f8237cbbb948072e3887796d4493099850e6000c63787bd8c08959de086ccd87"
    end
    on_arm do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
      sha256 "0c1a1e51712b953562af6333f31b22edcc681582013daf8ad46da4ceb5534f7f"
    end
  end

  # No zap stanza required
end
