# This file was generated by GoReleaser. DO NOT EDIT.
cask "kc" do
  name "kc"
  desc "Two-panel Kubernetes TUI built entirely with AI"
  homepage "https://github.com/sttts/kc"
  version "0.7.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kc"

  on_macos do
    on_intel do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
      sha256 "3bfa96ca827545a27632a270b7f57eb5e6f1766ae4959363f016f76601b5a8be"
    end
    on_arm do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
      sha256 "57515a18fdec30770d7e84ee6aa4d69dede0a607939d1d3391c8b09b58ba031a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
      sha256 "9323074ebe0d77c3bfb85420cab8b077a0fe4c52eb7ad1d72e7f919c1444de9a"
    end
    on_arm do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
      sha256 "fd7f2e4e1fb226d3a17f03165305ac3de5c836869b2da773d68dfc6f317cf3d4"
    end
  end

  # No zap stanza required
end
