# This file was generated by GoReleaser. DO NOT EDIT.
cask "kc" do
  name "kc"
  desc "Two-panel Kubernetes TUI built entirely with AI"
  homepage "https://github.com/sttts/kc"
  version "0.5.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kc"

  on_macos do
    on_intel do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
      sha256 "b2f32e96e94dad3860ee9ca7416e75141e999a9fdd90e70387e682bf143d5f0b"
    end
    on_arm do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
      sha256 "aadfef494b1c3c9f0fbaeaff309a93b5ddf8a9fc515d0ac473ceb6e4e64de4d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
      sha256 "5a899f9a110d231194dfe5e445d51dc4125348d685bfb04223ecf9d013d6e883"
    end
    on_arm do
      url "https://github.com/sttts/kc/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
      sha256 "b224f7550abb2beb06ff2f36cc12597856554abb55ddb6b09d238f7edb72955e"
    end
  end

  # No zap stanza required
end
