# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kc < Formula
  desc "Two-panel Kubernetes TUI built entirely with AI"
  homepage "https://github.com/sttts/kc"
  version "0.7.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/kc/releases/download/v0.7.3/kc_0.7.3_darwin_amd64.tar.gz"
      sha256 "218f0f25f7e387cca7c34b21ee2f7fa99ab1b049fcac335fd0c2386bdb6d6ebd"

      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/kc/releases/download/v0.7.3/kc_0.7.3_darwin_arm64.tar.gz"
      sha256 "27efacc6f4eb9b38da7025db3262a86b7232a1dce7954ce0552ba39ea3d85426"

      def install
        bin.install "kc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/kc/releases/download/v0.7.3/kc_0.7.3_linux_amd64.tar.gz"
      sha256 "3572b8028124195181870f9fec3d60153c8f1a47d721de24baf1f0095447104a"
      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/kc/releases/download/v0.7.3/kc_0.7.3_linux_arm64.tar.gz"
      sha256 "73f2b9645d48fac65d5dc07e75363e93948ae68e7176646d5a408e529724f7ea"
      def install
        bin.install "kc"
      end
    end
  end

  test do
    system "#{bin}/kc --version"
  end
end
