# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kc < Formula
  desc "Two-panel Kubernetes TUI built entirely with AI"
  homepage "https://github.com/sttts/kc"
  version "0.7.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/kc/releases/download/v0.7.4/kc_0.7.4_darwin_amd64.tar.gz"
      sha256 "3bfa96ca827545a27632a270b7f57eb5e6f1766ae4959363f016f76601b5a8be"

      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/kc/releases/download/v0.7.4/kc_0.7.4_darwin_arm64.tar.gz"
      sha256 "57515a18fdec30770d7e84ee6aa4d69dede0a607939d1d3391c8b09b58ba031a"

      def install
        bin.install "kc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/kc/releases/download/v0.7.4/kc_0.7.4_linux_amd64.tar.gz"
      sha256 "9323074ebe0d77c3bfb85420cab8b077a0fe4c52eb7ad1d72e7f919c1444de9a"
      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/kc/releases/download/v0.7.4/kc_0.7.4_linux_arm64.tar.gz"
      sha256 "fd7f2e4e1fb226d3a17f03165305ac3de5c836869b2da773d68dfc6f317cf3d4"
      def install
        bin.install "kc"
      end
    end
  end

  test do
    system "#{bin}/kc --version"
  end
end
